FROM golang:1.15-alpine

ARG git_commit

RUN apk add --no-cache gcc linux-headers libc-dev git perl-utils

RUN env

RUN go env

WORKDIR /src

ADD go.* /src/

RUN go mod download

ADD . /src

RUN GIT_COMMIT=${git_commit:-unknown} sh -x build-binaries.sh
