FROM golang:1.10-alpine

RUN apk add --no-cache gcc linux-headers libc-dev git

WORKDIR /go/src/github.com/orbs-network/boyarin/

ADD . /go/src/github.com/orbs-network/boyarin/

RUN env

RUN go env

RUN ./test.sh

RUN sh -x build-binaries.sh
