version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: ./git-submodule-checkout.sh
      - run: ./docker-build.sh
      - run: $(aws ecr get-login --no-include-email --region us-west-2)
      - run: docker pull $ORBS_NODE_DOCKER_IMAGE:master && docker tag $ORBS_NODE_DOCKER_IMAGE:master orbs:export
      # FIXME replace tag with master
      - run: docker pull $SIGNER_DOCKER_IMAGE:feature-signing-service-poc && docker tag $SIGNER_DOCKER_IMAGE:feature-signing-service-poc orbs:signer
      - run: docker swarm init
      - run:
          command: export DOCKER_IMAGE=$ORBS_NODE_DOCKER_IMAGE DOCKER_TAG=master ENABLE_SWARM=true  && ./docker-test.sh
          no_output_timeout: 20m

workflows:
  version: 2
  build:
    jobs:
      - build
