version: 2.1
jobs:
  test:
    docker:
      - image: circleci/golang:1.15
    environment: # environment variables for the build itself
      TEST_RESULTS: /tmp/test-results # path to where test results will be saved
    steps:
      - checkout # check out source code to working directory
      - run: mkdir -p $TEST_RESULTS # create the test results directory

      - restore_cache: # restores saved cache if no changes are detected since last run
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}

      - run:
          name: Run unit tests
          # store the results of our tests in the $TEST_RESULTS directory
          command: |
            PACKAGE_NAMES=$(go list ./... | circleci tests split --split-by=timings --timings-type=classname)
            gotestsum --junitfile ${TEST_RESULTS}/gotestsum-report.xml -- $PACKAGE_NAMES

      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"

      - store_test_results: # upload test results for display in Test Summary
          path: /tmp/test-results

  test-e2e:
    machine: true
    environment:
      TEST_RESULTS: /tmp/test-results # path to where test results will be saved
    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS # create the test results directory
      - run: .circleci/setup-machine.sh
      - docker/install-docker
      - run: |
          cat $BASH_ENV
          go version
          node --version
          env
          go env
          docker --version
      - run: ./.circleci/setup-e2e.sh
      - run: go mod download && go mod verify
      - run:
          name: run tests
          environment:
            ENABLE_SWARM: "true"
          command: |
            export LOCAL_IP=$(python -c "import socket; print socket.gethostbyname(socket.gethostname())")
            PACKAGE_NAMES=$(go list ./... | circleci tests split --split-by=timings --timings-type=classname)
            gotestsum --junitfile ${TEST_RESULTS}/gotestsum-report.xml -- -timeout 30m -p 1 $PACKAGE_NAMES
          no_output_timeout: 1h
      - store_test_results: # Upload test results for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: /tmp/test-results
orbs:
  docker: circleci/docker@0.5.19

workflows:
  version: 2
  build:
    jobs:
      - test
      - test-e2e
