version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    machine: true
    steps:
      - checkout
      - run: go test ./... -v
      - run: ./docker-build.sh
      - run: $(aws ecr get-login --no-include-email --region us-west-2)
      - run: docker pull $ORBS_NODE_DOCKER_IMAGE:master && docker tag $ORBS_NODE_DOCKER_IMAGE:master orbs:export
      - run: docker pull $SIGNER_DOCKER_IMAGE:master && docker tag $SIGNER_DOCKER_IMAGE:master orbs:signer
      - run: docker swarm init
      - run:
          command: export DOCKER_IMAGE=$ORBS_NODE_DOCKER_IMAGE DOCKER_TAG=master ENABLE_SWARM=true  && ./docker-test.sh
          no_output_timeout: 20m

workflows:
  version: 2
  build:
    jobs:
      - build
