version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: go test ./... -v

  build:
    machine: true
    steps:
      - checkout
      - run: ./docker-build.sh
      - run: $(aws ecr get-login --no-include-email --region us-west-2)
      - run: docker pull $ORBS_NODE_DOCKER_IMAGE:master
      - run: docker pull $SIGNER_DOCKER_IMAGE:master
      - run: docker tag $ORBS_NODE_DOCKER_IMAGE:master orbs:export
      - run: docker tag $SIGNER_DOCKER_IMAGE:master orbs:signer
      - run: docker swarm init
      - run: ./docker-test.sh

workflows:
  version: 2
  build:
    jobs:
      - test
      - build
